version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
  celery:
    build: .
    command: celery -A backend.celery:app worker --loglevel=info
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
  my_app:
    build: .  # Build context set to root directory
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app  # Map the current directory to /app in the container
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    entrypoint: ["/app/entrypoint.sh"]
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:8000"
volumes:
  db-data:
