global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: '/monitoring/metrics'
    static_configs:
      - targets: ['myapp:8000'] # Use the service name as the hostname
