# Generated by Django 4.2.5 on 2023-09-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_userqueries_correct_answers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
