name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Update to v2 since v3 might not exist yet

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --tag myapp:latest

    # Run the image (only if needed for tests)
    - name: Run the Docker container
      run: docker run -d --name myapp-container myapp:latest

    # Run the tests inside the Docker container
    - name: Run the tests inside the Docker container
      run: docker exec myapp-container python manage.py test
