name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the MyApp Docker image
      run: docker build . --file Dockerfile --tag myapp

    - name: Run MyApp Docker image
      run: docker run -d --name myapp_container myapp

    # If you want to build and run the other services, you can add similar steps.
    # For example, to build the Celery service:
    - name: Build the Celery Docker image
      run: docker build . --file Dockerfile.celery --tag celery

    # And to run it:
    - name: Run Celery Docker image
      run: docker run -d --name celery_container celery

    # Similarly, for the frontend:
    - name: Build the Frontend Docker image
      run: docker build ./frontend --file Dockerfile.frontend --tag frontend

    - name: Run Frontend Docker image
      run: docker run -d --name frontend_container frontend
