name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and start the Docker services
      run: docker-compose up -d

    - name: Check running services
      run: docker-compose ps

    - name: Sleep for 60 seconds to allow the database to initialize
      run: sleep 60

    # Run all migrations instead of just for the auth app.
    - name: Run Django migrations
      run: docker-compose run myapp python manage.py migrate

    - name: Show migrations
      run: docker-compose run --no-deps myapp python manage.py showmigrations

    - name: Display db logs
      run: docker-compose logs db

    - name: Display myapp logs
      run: docker-compose logs myapp

    # Test execution
    - name: Run tests (or other commands)
      run: docker-compose run myapp python manage.py test

    # Clean up
    - name: Stop Docker containers
      run: docker-compose down
