name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and start the Docker services
      run: docker-compose up -d

    # Wait for some time to allow the database to initialize
    - name: Sleep for 30 seconds
      run: sleep 30

    # Run the migrations on the myapp container
    - name: Run migrations
      run: docker-compose exec myapp python manage.py migrate

    # If needed, you can add other checks/tests here

    # Clean up the containers after the jobs are done
    - name: Stop Docker containers
      run: docker-compose down
