name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and start the Docker services
      run: docker-compose up -d

    # Wait for some time to allow the database to initialize

    - name: Check running services
      run: docker-compose ps

    # - name: Run make migrations
    #   run: docker-compose exec myapp python manage.py makemigrations


    - name: Check migrations status
      run: docker-compose exec myapp python manage.py showmigrations

    - name: Sleep for 30 seconds
      run: sleep 30

    - name: Run migrations
      run: docker-compose exec myapp python manage.py migrate

    - name: Display myapp logs
      run: docker-compose logs myapp

    - name: Display db logs
      run: docker-compose logs db

    - name: Run tests (or other commands)
      run: docker-compose exec myapp python manage.py test

    # If needed, you can add other checks/tests here

    # Clean up the containers after the jobs are done
    - name: Stop Docker containers
      run: docker-compose down

