name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myapp
    
    # Assuming your Docker image runs your app when started without a command
    - name: Run the Docker container
      run: docker run -d --name my_app myapp
    
    # Execute tests inside the running container
    # This assumes that your app has a management command or script to run tests
    # For Django, it's typically `python manage.py test`
    - name: Execute tests
      run: docker exec my_app python manage.py test

    # Optionally: Cleanup, stop and remove the container
    - name: Cleanup
      run: docker stop my_app && docker rm my_app
